# Generated by Django 2.0.1 on 2018-01-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='título', max_length=20, verbose_name='Título')),
                ('subtitle', models.TextField(default='subtitulo', max_length=40, verbose_name='Para')),
                ('status', models.BooleanField(default=1, verbose_name='Publicado')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_alteration', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
