# Generated by Django 2.0.1 on 2018-01-05 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nmcapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Services',
        ),
    ]
