# Generated by Django 2.0.1 on 2018-01-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmcapp', '0003_services_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='subtitle',
            field=models.TextField(default='A NMC Consultoria usa apenas informações atualizadas e novos métodos comerciais, fornecendo as soluções mais eficazes para o seu negócio', verbose_name='Subtitulo'),
        ),
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.TextField(default='título', max_length=60, verbose_name='Título'),
        ),
    ]
