# Generated by Django 2.0.1 on 2018-01-06 21:06

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('nmcapp', '0004_auto_20180106_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='título', max_length=60, verbose_name='Título')),
                ('subtitle', models.TextField(default='A NMC Consultoria usa apenas informações atualizadas e novos métodos comerciais, fornecendo as soluções mais eficazes para o seu negócio', verbose_name='Subtitulo')),
                ('text', tinymce.models.HTMLField(default='Texto')),
                ('status', models.BooleanField(default=1, verbose_name='Publicado')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_alteration', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='services',
            name='text',
            field=tinymce.models.HTMLField(default='Texto'),
        ),
    ]
